name: "filej0ker-dev"
services:
  db:
    image: "postgres:latest"
    container_name: filej0ker-dev-db
    ports: 
      - "5432:5432"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fjdb
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    
  backend:
    build:
      context: ./server
      target: development
    container_name: filej0ker-dev-backend
    ports: 
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./server/package.json
        - action: rebuild
          path: ./server/.env.development
        - action: sync
          path: ./server
          target: /app
    environment:
      - EXPRESS_PORT=5000
      - NODE_ENV=development
      - POSTGRES_URL=postgres://postgres:postgres@db:5432/fjdb
      - FRONTEND_URL=http://localhost:3000/
  
  web:
    build:
      context: ./web
      target: development
    container_name: filej0ker-dev-web
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
      - db
    develop:
      watch:
        - action: rebuild
          path: ./web/package.json
        - action: sync
          path: ./web
          target: /app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000/
