name: "filej0ker-dev"
services:
  db:
    image: "postgres:latest"
    container_name: filej0ker-dev-db
    ports: 
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fjdb
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    
  backend:
    build:
      context: ./server
      target: development
    container_name: filej0ker-dev-backend
    ports: 
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
        - action: rebuild
          path: ./server/package.json
    environment:
      - NODE_ENV=development
      - POSTGRES_URL=postgres://postgres:postgres@db:5432/fjdb