name: "filej0ker-test"
services:
  db:
    image: "postgres:latest"
    container_name: filej0ker-test-db
    ports: 
      - "5432:5432"
    restart: unless-stopped
    environment:
      - NODE_ENV=test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    
  backend:
    build:
      context: ./server
      target: development
    container_name: filej0ker-test-backend
    ports: 
      - "5000:5000"
    command: npm test
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./server/package.json
        - action: sync
          path: ./server
          target: /app
    environment:
      - EXPRESS_PORT=5000
      - NODE_ENV=test
      - POSTGRES_URL=postgres://postgres:postgres@db:5432/testdb